language: c

os:
  - linux

before_install:
  - sudo apt-get update -y
  - sudo add-apt-repository --yes ppa:webupd8team/java
  - sudo apt-get install oracle-java9-installer
  - sudo apt install oracle-java9-set-default
  - sudo apt-get install libncurses5-dev
  - sudo apt-get install git-core gnupg flex bison gperf
 
  - sudo apt-get install build-essential
  - sudo apt-get install zip
  - sudo apt-get install curl 
  - sudo apt-get install libc6-dev
  - sudo apt-get install libncurses5-dev:i386 
  - sudo apt-get install x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386
  - sudo apt-get install libgl1-mesa-glx:i386 libgl1-mesa-dev 
  - sudo apt-get install g++-multilib tofrodos python-markdown
  - sudo apt-get install libxml2-utils xsltproc zlib1g-dev:i386
  - sudo  ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
  - sudo apt-get install -y ccache &&echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc &&source ~/.bashrc && echo $PATH
  - export USE_CCACHE=1

before_script:
# Download te toolchain
  - git clone --depth=50 --branch=opt-linaro-7.x https://github.com/krasCGQ/aarch64-linux-android $HOME/LINARO/7.x

# Download the Kernel Sources
  - git clone --depth=50 --branch=Strakz-Oreo https://github.com/revanthstrakz/StRaKz_KeRnEl_Mido  $HOME/SK

# Download AnyKernel2
script:
  - export ARCH=arm64
  - export KERNELDIR=$HOME/SK
  - cd $HOME/SK
  - chmod a+x SK/scripts/kernel.sh
  - ./SK/scripts/kernel.sh
